AWSTemplateFormatVersion: 2010-09-09
Description: s3pypi repository


Outputs:
  DomainName:
    Value: !Ref DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
  BucketArn:
    Value: !GetAtt PyPIS3Bucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
  BucketDomainName:
    Value: !GetAtt PyPIS3Bucket.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-BucketDomainName'


Parameters:
  DomainName:
    Description: The (sub)domain that you want to use for your PyPI repository (e.g. pypi.yourcompany.com)
    Type: String


Resources:
  PyPIS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
